version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: abalone
      MYSQL_USER: dmy
      MYSQL_PASSWORD: 123
    volumes:
      - ./API/abalone.sql:/docker-entrypoint-initdb.d/abalone.sql
      - mysql_data:/var/lib/mysql
    network_mode: "host"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "dmy", "-p123" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: API.dockerfile
    environment:
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure:3
    network_mode: "host"

  websocket:
    build:
      context: .
      dockerfile: WSocket.dockerfile
    network_mode: "host"

    environment:
      NODE_ENV: development
    restart: on-failure:3

  frontend:
    build:
      context: .
      dockerfile: Frontend.dockerfile
    network_mode: "host"

    environment:
      NODE_ENV: development
    restart: on-failure:3

volumes:
  mysql_data:
